# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
    
    steps:
      - checkout

      - restore_cache:
          keys:
            - tfenv

      - run:
          name: Install dependencies
          command: |
            if [ ! -d ~/.tfenv ]; then
              git clone https://github.com/kamatama41/tfenv.git ~/.tfenv
            fi
            sudo ln -sf ~/.tfenv/bin/* /usr/bin

      - save_cache:
          key: tfenv
          paths:
            - ~/.tfenv

      - run: echo "run"

      - save_cache:
          key: tfenv
          paths:
            - ~/.tfenv
        
      - deploy:
          name: Deploy Bulktrade Portal
          command: |
           if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "develop" ]; then
             pushd aws/infra/accounts/prod
                tfenv install && \
                terraform init -upgrade && \
                terraform apply -auto-approve
             popd

             # build lambda
             ./aws/infra/modules/lambda/amazon-product-api/build.sh

             pushd  aws/infra/environments/p-fra
               tfenv install && \
               terraform init -upgrade && \
               terraform apply -auto-approve
             popd
           fi

      - run: echo "cleanup"
